name: publish

on:
  push:
    branches:
      - temp-ghaction
  schedule:
    - cron: "15 12 5,15,25 * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: supermomonga/weneedfeed-action@fix-gemfile-identification
        with:
          base_url: https://supermomonga.github.io/weneedfeed-magcomi
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output